### ISSUE TITLE
Breaks Bubbet's Items' Abstracted Locus?

### ISSUE THREAD

**Issue by acanthii** [elementGEMO/LunarsOfExiguity#2]
https://github.com/Bubbet/BubbetsItems/issues/12

Causes an issue with Bubbet's Items where the Abstracted Locus item (an item that changes the teleporter radius color, radius size, and applies a void fog effect when outside it) does not work with this mod installed.

**Comment by acanthii** [comment]
added on both ends cuz i have 0 clue what's causing this </3

**Comment by elementGEMO** [comment]
Fixed it.
